theme: jekyll-theme-minimal
title: Emma T. Boudreau
description: Personal website and portfolio
logo: /assets/images/headshot.jpg

# Optional: if you're planning to use posts
permalink: /:categories/:year/:month/:title/